services:
  app:
    build: .
    container_name: eduquery-app
    env_file:
      - .env
    environment:
      TZ: Asia/Jakarta
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./prompts:/app/prompts
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]